# ===============================
# PROFILE DE DESENVOLVIMENTO
# ===============================
# Ativar com: spring.profiles.active=dev
# Ou via variavel de ambiente: SPRING_PROFILES_ACTIVE=dev

# ===============================
# HIBERNATE - DESENVOLVIMENTO
# ===============================

spring.jpa.hibernate.ddl-auto=update

# ===============================
# LOGS - DESENVOLVIMENTO
# ===============================

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
